replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

run:
  command: 
    - /bin/sh
  args: 
    - -c
    - >
      ls -al . ;
      ls -al server; cat server/config.json;
      echo "Environment: {{ .Release.Namespace }}";
      node --max-old-space-size=4096 .

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"
  - name: secrets-volume
    secret:
      secretName: "{{ .Release.Name }}-s"

secrets: 
  "{{ .Release.Name }}-s":
    type: Opaque
    data: 
      component-config.json: "{{ .Values.secretsJson.COMPONENT_CONFIG }}"
      datasources.json: "{{ .Values.secretsJson.DATASOURCES }}"
      functionalAccounts.json: "{{ .Values.secretsJson.FUNCTIONAL_ACCOUNTS }}"
      providers.json: "{{ .Values.secretsJson.PROVIDERS }}"
      mail_auth: "{{ .Values.secretsJson.MAIL_AUTH }}"

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-be-certificate"

configMaps: 
  "{{ .Release.Name }}-cm":
    server.js: "{{ .Values.SERVER }}"
    config.local.js: "{{ .Values.CONFIG_LOCAL }}"
    login-callbacks.js: "{{ .Values.LOGIN_CALLBACKS }}"
    middleware.json: "{{ .Values.MIDDLEWARE }}"
    publishWhenFinished.js: "{{ .Values.PUBLISH_FINISHED }}"
    job-template.html: "{{ .Values.EMAIL_TEMPLATE }}"
    hideEmail.js: "{{ .Values.HIDE_EMAIL }}"

env:
  - name: ENV
    value: "{{ .Values.envValue }}"
  - name: MAIL_AUTH
    valueFrom:
      secretKeyRef: 
        name: "{{ .Release.Name }}-s"
        key: mail_auth

volumeMounts:
  - name: config-volume
    mountPath: /home/node/app/server/server.js
    subPath: server.js
  - name: config-volume
    mountPath: /home/node/app/server/config.local.js
    subPath: config.local.js
  - name: config-volume
    mountPath: /home/node/app/server/middleware.local.json
    subPath: middleware.json
  - name: config-volume
    mountPath: /home/node/app/server/boot/login-callbacks.js
    subPath: login-callbacks.js
  - name: config-volume
    mountPath: /home/node/app/server/boot/publishWhenFinished.js
    subPath: publishWhenFinished.js
  - name: config-volume
    mountPath: /home/node/app/email-templates/job-template.html
    subPath: job-template.html
  - name: config-volume
    mountPath: /home/node/app/server/boot/hideEmail.js
    subPath: hideEmail.js
  - name: secrets-volume
    mountPath: /home/node/app/server/providers.json
    subPath: providers.json
  - name: secrets-volume
    mountPath: /home/node/app/server/datasources.json
    subPath: datasources.json
  - name: secrets-volume
    mountPath: /home/node/app/server/functionalAccounts.json
    subPath: functionalAccounts.json
  - name: secrets-volume
    mountPath: /home/node/app/server/component-config.json
    subPath: component-config.json

probeChecks:
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 5 
