version: "3.9"
services:

  mongodb:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    profiles:
      - legacy
      - be
      - be_next
      - next
      - search_legacy
      - search_next
      - lp_legacy
      - lp_next
      - oi_next
      - oi_legacy
      - oi_lp

  backend:
    build: ../backend/.
    depends_on:
      - mongodb
    volumes:
      - ../backend:/home/node/app
      - ../backend/CI/ESS/envfiles/settings.sample.json:/home/node/app/test/config/settings.json
      - /home/node/app/node_modules
      - ./config/backend/config.local.js:/home/node/app/server/config.local.js
      - ./config/backend/datasources.json:/home/node/app/server/datasources.json
      - ./config/backend/providers.json:/home/node/app/server/providers.json
    environment:
      NODE_ENV: development
    command: /bin/sh -c "npm ci && while true; do sleep 600; done"
    profiles:
      - be
      - legacy
      - search_legacy
      - lp_legacy
      - oi_legacy
      - be_pr

  frontend:
    build: 
      context: ../frontend/.
      target: installer
      dockerfile: ../dev/config/frontend/Dockerfile
    environment:
      CHROME_BIN: /usr/bin/chromium
      CHROME_PATH: /usr/lib/chromium/
    volumes:
      - ../frontend:/frontend
      - ./config/frontend/config.json:/frontend/src/assets/config.json
      - /frontend/node_modules
      - /frontend/dist
    command: /bin/sh -c "apt-get update && apt-get install -y chromium && while true; do sleep 600; done"
    profiles:
      - legacy
      - fe
      - next

  backend_next:
    build: 
      context: ../scicat-backend-next/.
      target: dev
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ../scicat-backend-next:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/dist
    environment:
      MONGODB_URI: mongodb://mongodb:27017/scicat_next
      EXPRESS_SESSION_SECRET: a_scicat_secret
      JWT_SECRET: a_scicat_secret
      PORT: 3000
      HTTP_MAX_REDIRECTS: 5
      HTTP_TIMEOUT: 5000
      JWT_EXPIRES_IN: 3600
      SITE: SAMPLE-SITE
      PID_PREFIX: PID.SAMPLE.PREFIX
      DOI_PREFIX: DOI.SAMPLE.PREFIX
      METADATA_KEYS_RETURN_LIMIT: 100
      METADATA_PARENT_INSTANCES_RETURN_LIMIT: 100
    command: /bin/sh -c "while true; do sleep 600; done"
    profiles:
      - be_next
      - next
      - search_next
      - lp_next
      - oi_next

  jupyter:
    image: python:3.10
    ports:
     - 8888:8888
    volumes:
      - ../curation/requirements.txt:/requirements.txt
      - ../curation/notebooks:/notebooks
      - ./config/jupyter/.env:/.env
    command: /bin/sh -c "pip install --no-cache-dir -r requirements.txt && pip install jupyterlab && jupyter-lab --LabApp.token='' --allow-root --port=8888 --ip=0.0.0.0 --notebook-dir=/notebooks"
    profiles: 
      - jupyter

  search_api:
    build: 
      context: ../search-api/.
    volumes:
      - ../search-api:/home/node/app
      - /home/node/app/node_modules
    command: /bin/sh -c "npm ci && while true; do sleep 600; done"
    environment:
      NODE_ENV: development
    profiles:
      - search
      - search_next
      - search_legacy

  landing_page:
    build: 
      context: ../landing-page-server/.
      target: installer
      dockerfile: ../dev/config/landing-page-server/Dockerfile
    environment:
      CHROME_BIN: /usr/bin/chromium
      CHROME_PATH: /usr/lib/chromium/
    volumes:
      - ../landing-page-server:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/dist
    command: /bin/sh -c "apt-get update && apt-get install -y chromium && while true; do sleep 600; done"
    user: 0:0
    profiles:
      - lp
      - lp_next
      - lp_legacy
      - oi_lp

  oaipmh:
    build: ../oaipmh/.
    volumes:
      - ../oaipmh:/home/node/app
      - ./config/oaipmh/.env:/home/node/app/production/.env
      - /home/node/app/node_modules
      - /home/node/app/dist
    command: /bin/sh -c "npm ci && while true; do sleep 600; done"
    profiles:
      - oi
      - oi_next
      - oi_legacy
      - oi_lp

  proposals:
    build:
      context: ../proposals/.
      target: dev
    volumes:
      - ../proposals:/usr/src/proposals
      - ./config/proposals/.env:/usr/src/proposals/.env
    # infinite loop to keep the container running
    command: /bin/sh -c "while sleep 1000; do :; done"
    profiles:
      - pr
      - be_pr

volumes:
  mongodb_data:
    driver: local
