replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3001

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite "(?i)/oaipmh/oai" /scicat/oai break;
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: /openaire/oai
          pathType: Exact
        - path: /oaipmh/oai
          pathType: Exact
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-oaipmh-certificate"

volumes:
  - name: secrets-volume
    secret:
      secretName: "{{ .Release.Name }}-s"

secrets: 
  "{{ .Release.Name }}-s":
    type: Opaque
    data: 
      .env: '${{ secrets.OAIPMH_ENV }}'

volumeMounts:
  - name: secrets-volume
    mountPath: /home/node/app/dist/server/.env
    subPath: .env
