replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-certificate"

volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"
  - name: downloaddir
    emptyDir: {}

initialDelaySeconds: 360

configMaps: 
  "{{ .Release.Name }}-cm":
    environment.ts: "{{ .Values.ciVars.ENVIRONMENT }}"
    keycloak-icon-256px.svg: "{{ .Values.ciVars.KEYCLOAK_ICON }}"
    styles.scss: "{{ .Values.ciVars.STYLES }}"

initContainers:
  - name: install
    image: busybox
    command:
      - wget
      - "-O"
      - "/download-dir/site.png"
      - https://raw.githubusercontent.com/paulscherrerinstitute/scicat-ci/7727f506c8f4d7f1f5b296e0ff80501e262866d9/helm_configs/frontend/site.png
    volumeMounts:
      - name: downloaddir
        mountPath: "/download-dir"
