name: deploy-helm
description: "Helm deploy"

inputs:
  secrets: 
    description: secrets to be set when creating the secret resource
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        mkdir .ssh;
        echo ${{ inputs.bastion_ssh_key }} > .ssh/github_bastion;
        ssh -D 1080 -f -q -N ${{ inputs.bastion_user }} -i .ssh/github_bastion;
      shell: bash
