name: deploy-helm
description: "Helm deploy"

inputs:
  bastion_user: 
    description: username@host for the ssh tunnel
    required: true
    type: string
  bastion_ssh_key: 
    description: private ssh key content
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        mkdir .ssh;
        echo ${{ inputs.bastion_ssh_key }} | base64 -d > .ssh/github_bastion;
        ssh -D 1080 -f -q -N ${{ inputs.bastion_user }} -i .ssh/github_bastion;
      shell: bash
