# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: "busybox"
  tag: latest
cronjob:
  restartPolicy: OnFailure
  schedule: 0 7 * * 1

# Business logic
duo_facilities:
 - name: pgroups
   schedule: 0 2 * * 4
 - name: sls
   schedule: 30 3 * * 1,3,5
 - name: swissfel
   schedule: 30 4 * * 1,3,5
 - name: smus
   schedule: 0 5 * * 4
 - name: sinq
   schedule: 0 3 * * 6
   year: 2020
 - name: sinq
   schedule: 30 3 * * 6
   year: 2021
 - name: sinq
   schedule: 0 4 * * 6

# Potentially add required env vars here, to ease local development
#duo_endpoint: ""
#duo_secret: ""
#scicat_username: ""
#scicat_password: ""
#scicat_endpoint: ""
