env:
  - name: NODE_ENV
    value: development

volumeMounts:
  - name: config-volume
    mountPath: /usr/src/app/server/config.local.js
    subPath: config.local.js
  - name: config-volume
    mountPath: /usr/src/app/server/middleware.development.json
    subPath: middleware.development.json
  - name: config-volume
    mountPath: /usr/src/app/server/boot/login-callbacks.js
    subPath: login-callbacks.js
  - name: secrets-volume
    mountPath: /usr/src/app/server/providers.json
    subPath: providers.json
  - name: secrets-volume
    mountPath: /usr/src/app/server/datasources.development.json
    subPath: datasources.json
  - name: secrets-volume
    mountPath: /usr/src/app/server/datasources.json
    subPath: datasources.json
  - name: secrets-volume
    mountPath: /usr/src/app/server/functionalAccounts.json
    subPath: functionalAccounts.json
  - name: secrets-volume
    mountPath: /usr/src/app/server/component-config.development.json
    subPath: component-config.json

configMaps: 
  "{{ .Release.Name }}-cm":
    config.local.js: "{{ .Values.ciVars.CONFIG_LOCAL }}"
    login-callbacks.js: "{{ .Values.ciVars.LOGIN_CALLBACKS }}"
    middleware.development.json: "{{ .Values.ciVars.MIDDLEWARE }}"

host: scicat.development.psi.ch
