replicaCount: 1

image:
  repository: "{{ .Values.ciRepository }}"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Values.ciTag }}"

run:
  command: 
    - /bin/sh
  args: 
    - -c
    - >
      ls -al . ;
      ls -al server; cat server/config.json;
      echo "Environment: {{ .Release.Namespace }}";
      node --max-old-space-size=4096 .

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

volumes:
  - name: config-volume
    configMap:
      name: "{{ .Release.Name }}-cm"
  - name: secrets-volume
    secret:
      secretName: "{{ .Release.Name }}-s"

secrets: 
  "{{ .Release.Name }}-s":
    type: Opaque
    data: 
      component-config.json: '${{ secrets.COMPONENT_CONFIG }}'
      datasources.json: '${{ secrets.DATASOURCES }}'
      functionalAccounts.json: '${{ secrets.FUNCTIONAL_ACCOUNTS }}'
      providers.json: '${{ secrets.PROVIDERS }}'
      mail_auth: '${{ secrets.MAIL_AUTH }}'

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - host: "{{ .Values.host }}"
      paths: 
        - path: "/api"
          pathType: Prefix
        - path: "/explorer"
          pathType: Prefix
        - path: "/auth"
          pathType: Prefix
  tls:
    - hosts:
      - "{{ .Values.host }}"
      secretName: "scicat-certificate"

configMaps: 
  "{{ .Release.Name }}-cm":
    config.local.js: "{{ .Values.ciVars.CONFIG_LOCAL }}"
    login-callbacks.js: "{{ .Values.ciVars.LOGIN_CALLBACKS }}"
    middleware.json: "{{ .Values.ciVars.MIDDLEWARE }}"
    publishWhenFinished.js: "{{ .Values.ciVars.PUBLISH_FINISHED }}"

env:
  - name: ENV
    value: "{{ .Values.envValue }}"
  - name: MAIL_AUTH
    valueFrom:
      secretKeyRef: 
        name: "{{ .Release.Name }}-s"
        key: mail_auth

volumeMounts:
  - name: config-volume
    mountPath: /usr/src/app/server/config.local.js
    subPath: config.local.js
  - name: config-volume
    mountPath: /usr/src/app/server/middleware.local.json
    subPath: middleware.json
  - name: config-volume
    mountPath: /usr/src/app/server/boot/login-callbacks.js
    subPath: login-callbacks.js
  - name: config-volume
    mountPath: /usr/src/app/server/boot/publishWhenFinished.js
    subPath: publishWhenFinished.js
  - name: secrets-volume
    mountPath: /usr/src/app/server/providers.json
    subPath: providers.json
  - name: secrets-volume
    mountPath: /usr/src/app/server/datasources.json
    subPath: datasources.json
  - name: secrets-volume
    mountPath: /usr/src/app/server/functionalAccounts.json
    subPath: functionalAccounts.json
  - name: secrets-volume
    mountPath: /usr/src/app/server/component-config.json
    subPath: component-config.json
