volumeMounts:
  - name: config-volume
    mountPath: /usr/src/app/src/environments/environment.qa.ts
    subPath: environment.ts
  - name: config-volume
    mountPath: /usr/src/app/src/assets/images/keycloak_icon_256px.svg
    subPath: keycloak-icon-256px.svg

env:
  - name: env
    value: qa

host: scicat.qa.psi.ch
