name: build-deploy-scicat-component

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      image_name:
        required: true
        type: string
      helm_ci_vars:
        required: false
        type: string
        default: "{}"
      release_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:

  build:
    uses: ./.github/workflows/build.yml
    with: 
      context: backend/.
      registry: ghcr.io
      image_name: ${{ github.repository }}
      tag: ${{ inputs.tag }}
      push_condition: ${{ github.event_name == 'pull_request' }}

  deploy:

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: 
      - build

    steps:

    - name: Deploy to k8s using helm
      id: helm-deploy
      uses: 'glopezep/helm@v1.7.1'
      with:
        release: '${{ inputs.release_name }}'
        namespace: 'scicat-${{ inputs.environment }}'
        chart: 'generic_service_chart'
        helm: helm3
        values: |
         ciRepository: ghcr.io/${{ github.repository }}
         ciTag: ${{ inputs.tag }}
         ciVars: ${{ inputs.helm_ci_vars }}
        value-files: "helm_configs/${{ inputs.environment }}/values.yaml"
        secrets: '${{ toJSON(secrets) }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
