name: build-deploy

on:  
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RELEASE_NAME: scicat-be
  TAG: ${{ github.event.pull_request.head.sha }}
  HOST: scicat.development.psi.ch

jobs:

  build-deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Set helm var
      id: helm_vars
      run: |
        ciVars=$(cat <<EOF
        {
          "repository": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}",
          "tag": "${{ env.TAG }}",
          "host": "${{ env.HOST }}"
        }
        EOF
        )
        echo "::set-output name=ciVars::$(echo $ciVars)"

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set helm configmaps
      id: helm_configmaps
      run: |
        configMaps=$(cat <<EOF
        {
          "${{ env.RELEASE_NAME }}-cm": 
            {
              "config.local.js": $(jq -R -s < helm_configs/development/catamel_cm/config.local.js),
              "login-callbacks.js": $(jq -R -s < helm_configs/development/catamel_cm/login-callbacks.js),
              "middleware.development.json": $(jq -R -s < helm_configs/development/catamel_cm/middleware.development.json)
            }
        }
        EOF
        )
        echo "::set-output name=configMaps::$(echo $configMaps)"

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{github.event.pull_request.head.sha}}
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: backend/.
        push: ${{ github.event_name == 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy to k8s using helm
      id: helm-deploy
      uses: 'glopezep/helm@v1.7.1'
      with:
        release: '${{ env.RELEASE_NAME }}'
        namespace: 'scicat-development'
        chart: 'generic_service_chart'
        helm: helm3
        values: |
         configMaps: ${{ steps.helm_configmaps.outputs.configMaps }}
         ciVars: ${{ steps.helm_vars.outputs.ciVars }}
        value-files: "helm_configs/development/values.yaml"
        secrets: '${{ toJSON(secrets) }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
