name: set-environment

on:
  workflow_call:
    outputs:
      tag:
        description: tag of the docker image
        value: ${{ jobs.set_env.outputs.tag }}
      environment:
        description: environment based on workflow trigger
        value: ${{ jobs.set_env.outputs.environment }}
      component:
        description: Based on tag prefix, it extracts the component released
        value: ${{ jobs.set_env.outputs.component }}
        
jobs:

  set_env:
    name: Output
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.variables.outputs.tag }}
      environment: ${{ steps.variables.outputs.environment }}
    steps:
      - id: variables
        run: | 
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            tag="sha-${{ github.event.pull_request.head.sha }}"
            environment=development
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]]; then
              tag="sha-${{ github.sha }}"
              environment=qa
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            tag="${{ github.event.release.tag_name }}"
            environment=production
            component=${tag:0:2}
          fi
          echo "::set-output name=tag::$(echo $tag)"
          echo "::set-output name=environment::$(echo $environment)"
          echo "::set-output name=component::$(echo $component)"
