name: changes

on:
  workflow_call:
    inputs:
      files:
        required: true
        type: string
    outputs:
      changed:
        description: boolean to check if changes on input files
        value: ${{ jobs.changed.outputs.changed }}
    secrets: 
      SSH_PRIVATE_KEY: 
        description: ssh key to private submodule
        required: false

jobs:
  changed:
  
    runs-on: ubuntu-latest
    name: Check changed-files
    outputs:
      changed: ${{ steps.changed-files.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with: 
          files: ${{ inputs.files }}
