name: changes

on:
  workflow_call:
    inputs:
      files:
        required: true
        type: string
    outputs:
      changed:
        description: boolean to check if changes on input files
        value: ${{ jobs.changed.outputs.changed }}


jobs:
  changed:
  
    runs-on: ubuntu-latest
    name: Check changed-files
    outputs:
      changed: ${{ steps.changed-files-specific.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with: 
          files: ${{ inputs.changed_files }}

      - name: Run step if any of the listed files above change
        run: |
          echo "${{ steps.changed-files-specific.outputs.any_changed }}"
