name: scicat-to-pss

on:  
  workflow_dispatch: 
    inputs:
      commit: 
        description: 'Commit of the CI repo to deploy'     
        required: false
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  set_env: 
    uses: ./.github/workflows/reusable.environment.yml
    with: 
      commit: ${{ github.event.inputs.commit }}

  check_changed:
    needs: set_env
    uses: ./.github/workflows/reusable.changes.yml
    with: 
      files: | 
        .github/workflows/scicat-to-pss.yml
        helm/configs/scicat-to-pss/${{ needs.set_env.outputs.environment }}/**
        helm/configs/scicat-to-pss/values.yaml
        scicat-to-pss/**
      commit: ${{ needs.set_env.outputs.commit }}

  build_deploy:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'sp'
    needs: 
     - check_changed
     - set_env
    uses: ./.github/workflows/reusable.build-deploy.yml
    with: 
      context: scicat-to-pss/.
      image_name: ${{ github.repository }}/scicat-to-pss
      release_name: scicat-to-pss
      tag: ${{ needs.set_env.outputs.tag }}
      environment: ${{ needs.set_env.outputs.environment }}
      helm_chart: helm/charts/cron
      commit: ${{ needs.set_env.outputs.commit }}
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      BASTION_USER: ${{ secrets.BASTION_USER }}
      BASTION_SSH_KEY: ${{ secrets.BASTION_SSH_KEY }}
