name: scicat-be

on:  
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:

  set_env: 
    uses: ./.github/workflows/reusable.environment.yml

  check_changed:
    needs: set_env
    uses: ./.github/workflows/reusable.changes.yml
    with: 
      files: | 
        .github/workflows/scicat-be.yml
        helm_configs/backend/values.yaml
        helm_configs/backend/login-callbacks.js
        helm_configs/backend/job-tempate.html
        helm_configs/backend/config.local.js
        helm_configs/backend/${{ needs.set_env.outputs.environment }}/**
        backend/**

  set_ci_vars:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'be'
    runs-on: ubuntu-latest
    needs: 
      - check_changed
      - set_env
    outputs:
      ciVars: ${{ steps.helm_vars.outputs.ciVars }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set helm vars
      id: helm_vars
      run: |
        ciVars=$(cat <<EOF
          {
            "CONFIG_LOCAL": $(jq -R -s < helm_configs/backend/config.local.js),
            "LOGIN_CALLBACKS": $(jq -R -s < helm_configs/backend/login-callbacks.js),
            "MIDDLEWARE": $(jq -R -s < helm_configs/backend/${{ needs.set_env.outputs.environment }}/middleware.json),
            "PUBLISH_FINISHED": $(jq -R -s < helm_configs/backend/publishWhenFinished.js),
            "EMAIL_TEMPLATE": $(jq -R -s < helm_configs/backend/job-tempate.html),
          }
        EOF
        )
        echo "::set-output name=ciVars::$(echo $ciVars)"

  build_deploy_scicat_be:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'be'
    needs: 
     - check_changed
     - set_env
     - set_ci_vars
    uses: ./.github/workflows/reusable.build-deploy-scicat-component.yml
    with: 
      context: backend/.
      image_name: ${{ github.repository }}/be
      helm_ci_vars: ${{ needs.set_ci_vars.outputs.ciVars }}
      release_name: backend
      tag: ${{ needs.set_env.outputs.tag }}
      environment: ${{ needs.set_env.outputs.environment }}
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      JSON_SECRETS: ${{ toJSON(secrets) }}
