name: scicat-pan-ontologies-api

on:  
  workflow_dispatch: 
    inputs:
      submodule_commit:
        description: 'Commit of the submodule to deploy'     
        required: false
      commit: 
        description: 'Commit of the CI repo to deploy'     
        required: false
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:

  set_env: 
    uses: ./.github/workflows/reusable.environment.yml
    with: 
      commit: ${{ github.event.inputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}

  check_changed:
    needs: set_env
    uses: ./.github/workflows/reusable.changes.yml
    with: 
      files: | 
        .github/workflows/scicat-pan-ontologies-api.yml
        helm_configs/pan-ontologies-api/values.yaml
        helm_configs/pan-ontologies-api/${{ needs.set_env.outputs.environment }}/**
        pan-ontologies-api/**
      commit: ${{ needs.set_env.outputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}
      submodule: pan-ontologies-api

  build_deploy_scicat_pan_ontologies_api:
    if: (needs.check_changed.outputs.changed == 'true' && !needs.set_env.outputs.component) || needs.set_env.outputs.component == 'po'
    needs: 
     - check_changed
     - set_env
    uses: ./.github/workflows/reusable.build-deploy.yml
    with: 
      context: pan-ontologies-api/.
      image_name: ${{ github.repository }}/pan-ontologies-api
      release_name: pan-ontologies-api
      tag: ${{ needs.set_env.outputs.tag }}
      environment: ${{ needs.set_env.outputs.environment }}
      commit: ${{ needs.set_env.outputs.commit }}
      submodule_commit: ${{ github.event.inputs.submodule_commit }}
      submodule: pan-ontologies-api
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      JSON_SECRETS: ${{ toJSON(secrets) }}

